edge:
  type: varnish:5.1
  relationships:
    main: 'app:http'
  configuration:
    vcl: !include
      type: string
      path: config.vcl

multiedge:
  type: varnish:5.1
  relationships:
    everything: 'app:http'
    other: 'other:http'
  configuration:
    vcl: !include
      type: string
      path: multiconfig.vcl
