name: lando-platformsh-mysql
recipe: platformsh
config:
  id: DISCONNECTED


# This is important because it lets lando know to test against the plugin in this repo
plugins:
  "@lando/platformsh": ./../../
