# .platform/applications.yaml
- name: php
  type: "php:7.3"
  disk: 1024
  source:
    root: php
  build:
    flavor: composer
  web:
    locations:
      "/":
        root: "web"
        passthru: "/index.php"
  mounts:
    'web/files':
      source: local
      source_path: files
    'private':
      source: local
      source_path: private
  relationships:
    maria: 'db:mysql'
