name: advanced
type: "php:5.4"
runtime:
  extensions:
    - redis
dependencies:
  php:
    "platformsh/client": "2.x-dev"
    "composer/composer": "^2"
build:
  flavor: composer
hooks:
  build: |
    set -e
    touch /tmp/build
  deploy: |
    set -e
    touch /tmp/deploy

web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
  commands:
    start: /usr/sbin/php-fpm8.0-zts
