# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "edge:http"
  cache:
    enabled: false

"https://multi.{default}/":
  type: upstream
  upstream: "multiedge:http"
  cache:
    enabled: false

"https://multi.{default}/other/":
  type: upstream
  upstream: "multiedge:http"
  cache:
    enabled: false
