name: advanced
type: "php:7.0"
runtime:
  extensions:
    - redis
dependencies:
  php:
    "composer/composer": "^2"
build:
  flavor: composer
hooks:
  build: |
    set -e
    touch /tmp/build
  deploy: |
    set -e
    touch /tmp/deploy

web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
  commands:
    start: /usr/sbin/php-fpm7.0
