name: app
type: "php:7.3"
disk: 1024
build:
  flavor: composer
web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
relationships:
  mariadb: "mariadb:mysql"
  database: "multi:admin"
  reports: "multi:reporter"
  imports: "multi:importer"
