name: discreet
type: "php:7.2"
web:
  locations: !include
    type: yaml
    path: locations.yaml
variables: !include "variables.yaml"
properties:
  favicon: !include
    type: binary
    path: favicon.ico
