name: app
type: "php:7.3"
build:
  flavor: composer
runtime:
  extensions:
    - memcached
web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
relationships:
  cache: "cache:memcached"
