name: app
type: "php:7.3"
disk: 1024
build:
  flavor: composer
web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
relationships:
  mariadb: 'mariadb:mysql'
mounts:
  'files':
    source: local
    source_path: files
  'private':
    source: local
    source_path: private
