name: lando-platformsh-mongodb-3.6
recipe: platformsh
config:
  id: DISCONNECTED
tooling:
  mongo:
    service: mongo

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/platformsh": ./../../
