name: lando-platformsh-mariadb-10.0
recipe: platformsh
config:
  id: DISCONNECTED
excludes:
  - vendor
  - files
  - private

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/platformsh": ./../../
