name: lando-platformsh-postgresql-9.3
recipe: platformsh
config:
  id: DISCONNECTED


# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/platformsh": ./../../
