name: lando-platformsh-solr-4.10
recipe: platformsh
config:
  id: DISCONNECTED


# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/platformsh": ./../../
