mariadb:
  type: mariadb:10.2
  disk: 512
  configuration:
    properties:
      max_allowed_packet: 33

multi:
  type: mariadb:10.2
  disk: 2048
  configuration:
    schemas:
      - main
      - legacy
    endpoints:
      admin:
        default_schema: main
        privileges:
          main: admin
          legacy: admin
      reporter:
        privileges:
          main: ro
      importer:
        default_schema: legacy
        privileges:
          legacy: rw
