name: app
type: "php:7.3"
build:
  flavor: composer
web:
  locations:
    "/":
      root: "."
      passthru: "/index.php"
relationships:
  search: "search:solr"
  main: 'multicore:main'
  extra: 'multicore:extra'
  english: 'configset:english'
  arabic: 'configset:arabic'
