search:
  type: solr:8.6
  disk: 1024

multicore:
  type: solr:8.6
  disk: 1024
  configuration:
    cores:
      mainindex:
        conf_dir: !archive "core1-conf"
      extraindex:
        conf_dir: !archive "core2-conf"
    endpoints:
      main:
        core: mainindex
      extra:
        core: extraindex

#NOTE: the configset config was a bit confusing here. i thought it would work like the core setup above
# however you need to explicitly have a "conf" directory in the config set path set configsets/solr8/conf in
# the below example. I _expected_ configsets/solr8 to get dumped into /mnt/data/solr/configsets/mainconfig/conf
# but it gets dumped into /mnt/data/solr/configsets/mainconfig
configset:
  type: solr:8.6
  disk: 1024
  configuration:
    configsets:
      mainconfig: !archive "configsets/solr8"
    cores:
      english_index:
        core_properties: |
          configSet=mainconfig
          schema=schema.xml
      arabic_index:
        core_properties: |
          configSet=mainconfig
          schema=schema-plus.xml
    endpoints:
      english:
        core: english_index
      arabic:
        core: arabic_index
