name: lando-platformsh-basics
recipe: platformsh
config:
  id: om2hlkobxcbwe
  variables:
    php:
      env:
        APP_ENV: lando
  overrides:
    discreet:
      variables:
        env:
          STUFF: omg
    db:
      configuration:
        properties:
          max_allowed_packet: 63

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/platformsh": ./../../
