name: MySQL Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-tests:
          - mysql-10.0
          - mysql-10.1
          - mysql-10.2
          - mysql-10.3
          - mysql-10.4
        lando-versions:
          - 3-dev
        os:
          - ubuntu-22.04
        node-version:
          - '16'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            plugins.@lando/platformsh=/home/runner/work/platformsh/platformsh
          telemetry: false
      - name: Move in lando config appropriate for testing
        run: |
          mkdir -p ~/.lando/cache
          cp -f actions-lando-config.yml ~/.lando/config.yml
          echo false > ~/.lando/cache/report_errors
          lando --clear
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando version
          lando config --path plugins | grep platformsh | grep /home/runner/work/platformsh/platformsh || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
          cd ${{ matrix.leia-tests }}
          lando config --path plugins | grep platformsh | grep dir | grep /home/runner/work/platformsh/platformsh || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./examples/${{ matrix.leia-tests }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
