name: MySQL/MariaDB Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-tests:
          - platform-sh-maria-db-example
        lando-versions:
          - edge
        os:
          - ubuntu-20.04
        node-version:
          - '14'

    steps:

      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # This block should eventually become use lando/actions-hyperdrive@v2
      - name: Verify Docker dependencies
        run: |
          docker --version | grep "20.10."
          docker-compose --version | grep "1.29."
      - name: Grab latest edge Lando CLI
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
          sudo chmod +x /usr/local/bin/lando
      - name: Move in lando config appropriate for testing
        run: |
          mkdir -p ~/.lando/cache
          cp -f test-config.yml ~/.lando/config.yml
          echo false > ~/.lando/cache/report_errors
      # @NOTE:
      # It would be SO COOL to run tests against both STABLE and EDGE with failures allowed on EDGE?
      - name: Verify Lando works as we expect
        run: |
          sudo apt-get --yes purge mysql-server mysql-client || true
          sudo apt-get --yes autoremove --purge  || true
          sudo apt-get autoclean  || true
          sudo deluser --remove-home mysql  || true
          sudo delgroup mysql  || true
          sudo rm -rf /etc/apparmor.d/abstractions/mysql /etc/apparmor.d/cache/usr.sbin.mysqld /etc/mysql /var/lib/mysql /var/log/mysql* /var/log/upstart/mysql.log* /var/run/mysqld  || true
          sudo updatedb  || true

          lando version
          lando config
          cd examples/mariadb
          lando --clear
          lando config
          lando start -vvv
          docker inspect landoplatformshmysql_mariadb_1
          lando ssh -s mariadb -u root -c "cat /etc/platform/templates/my.cnf"
          lando ssh -s mariadb -u root -c "ls -lsa /etc/platform/templates"
          lando ssh -s mariadb -u root -c "ls -lsa /run/.configs/etc/platform/templates/my.cnf"
          # lando ssh -s mariadb -u root -c "chown -Rv app:app /run/.configs/etc/platform/templates"
          lando ssh -s mariadb -u root -c "rm -f /etc/platform/templates/my.cnf"
          lando ssh -s mariadb -u root -c "cp -f /run/.configs/etc/platform/templates/my.cnf /etc/platform/templates/my.cnf"
          lando ssh -s mariadb -u root -c "/etc/service/mysql-standalone/run" || true
          lando ssh -s mariadb -u root -c "ls -lsa /mnt/data/mysql"
          # docker ps -a
          # lando logs
          # sleep 100
          # lando ssh -s mariadb -u root -c "ps axf"
          # lando ssh -s mariadb -u root -c "/etc/service/mysql-standalone/run"
          # lando mariadb main -e "show tables;"

      # This block should eventually become use lando/actions-leia@v2
      # - name: Generate tests
      #   run: yarn generate:tests
      # - name: Run ${{ matrix.leia-tests }} tests
      #   run: yarn mocha --timeout 900000 ./test/${{ matrix.leia-tests }}.func.js
