name: PHP Tests

on:
  pull_request:

jobs:
  leia-test:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-test:
          - examples/php-8.0
          - examples/php-7.4
          - examples/php-7.3
          - examples/php-7.2
          - examples/php-7.1
          - examples/php-7.0
          - examples/php-5.6
          - examples/php-5.5
          # - examples/php-5.4
        lando-version:
          - 3-dev-slim
        os:
          - ubuntu-22.04
        node-version:
          - '18'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/platformsh=/home/runner/work/platformsh/platformsh
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
